version: "3.9"
services:
  dremio:
    platform: linux/x86_64
    hostname: dremio
    container_name: dremio
    image: dremio/dremio-oss:25.1
    env_file:
      - .env
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010

  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z-cpuv1
    hostname: minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./mnt/minio/data:/data
  
  # spark_notebook:
  #   image: alexmerced/spark33-notebook
  #   ports: 
  #     - 8888:8888
  #   env_file:
  #     - .env
  #   container_name: notebook
  
  nessie:
    image: projectnessie/nessie:0.76.6
    container_name: nessie
    hostname: nessie
    ports:
      - 19120:19120
  
  metabase:
    image: metabase/metabase:v0.50.26.1
    container_name: metabase
    hostname: metabase
    volumes:
      - ./mnt/metabase-plugins:/app/plugins
    ports:
      - 3000:3000
    env_file:
      - .env

networks:
  default:
    name: data-net
    driver: bridge

