version: "3.9"
services:
  dremio:
    platform: linux/x86_64
    hostname: dremio
    container_name: dremio
    image: dremio/dremio-oss
    env_file:
      - .env
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - ./mnt/minio/data:/data
  
  spark_notebook:
    image: alexmerced/spark33-notebook
    ports: 
      - 8888:8888
    env_file:
      - .env
    container_name: notebook
  
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    hostname: nessie
    ports:
      - "19120:19120"

networks:
  default:
    name: data-net
    driver: bridge

